---
- name: Converge
  hosts: all
  gather_facts: true
  roles:
    - semaphore
  pre_tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true
      when:
        - ansible_facts.os_family == "Debian"

    - name: Update dnf cache
      ansible.builtin.dnf:
        update_cache: true
      when:
        - ansible_facts.os_family == "RedHat"
