---

- name: Make sure semaphore_type is valid
  ansible.builtin.assert:
    that:
      - semaphore_type in ['server', 'runner']
    fail_msg: >-
      semaphore_type must be either 'server' or 'runner', got '{{ semaphore_type }}'!
      Check the Collection README for more information.
  tags: always

- name: Include OS-specific vars
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_facts.distribution }}_{{ ansible_facts.distribution_major_version }}.yml"
    - "{{ ansible_facts.distribution }}.yml"
    - "{{ ansible_facts.os_family }}.yml"
    - main.yml # avoid error when no distro vars file is found
  tags: always

- name: Install Semaphore UI in Docker
  ansible.builtin.import_tasks: install.yml
  tags:
    - "role::semaphore"
    - "role::semaphore:install"

- name: Configure Semaphore UI Server in Docker
  ansible.builtin.import_tasks: config-server.yml
  when: semaphore_type == 'server'
  tags:
    - "role::semaphore"
    - "role::semaphore:config"
    - "role::semaphore:config-server"

- name: Configure Semaphore UI Runner(s) in Docker
  ansible.builtin.import_tasks: config-runner.yml
  when: semaphore_type == 'runner'
  tags:
    - "role::semaphore"
    - "role::semaphore:config"
    - "role::semaphore:config-runner"
