---
name: Ansible Molecule
on: [push, pull_request]

permissions: {}

jobs:
  test:
    runs-on: ubuntu-24.04 # ubuntu latest will for all RHEL-based distros: https://github.com/rocky-linux/sig-cloud-instance-images/issues/56
    container:
      image: python:3.14@sha256:4fad23465a06cc5149a541fbec6f87e234a64dc0550f6bfdd2d290d8f03240df
    strategy:
      fail-fast: false
      matrix:
        config:
          - image: "debian13"
          - image: "fedora43"
          - image: "ubuntu2404"
          - image: "rockylinux9"
        scenario:
          - default
          - caddy-dns
    steps:
      - name: checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          path: "${{ github.repository }}"
          persist-credentials: false

      - name: molecule
        uses: gofrolist/molecule-action@8e92d9b8559e1811ff4d696792f209030d29bf64 # v2.9.8
        with:
          molecule_working_dir: "${{ github.repository }}/extensions"
          molecule_args: "-s ${{ matrix.scenario }}"
        env:
          image: ${{ matrix.config.image }}
